# This values.yaml file creates the resources for Qwen/Qwen3-0.6B
multinode: false

modelArtifacts:
  uri: "hf://meta-llama/Llama-3.1-70B"
  size: 160Gi
  authSecretName: "llm-d-hf-token"
  name: meta-llama/Llama-3.1-70B

routing:
  modelName: meta-llama/Llama-3.1-70B
  servicePort: 8000

  proxy:
    image: ghcr.io/llm-d/llm-d-routing-sidecar:v0.2.0
    secure: false
    connector: nixlv2

  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: infra-inference-scheduling-inference-gateway

  inferenceModel:
    create: false

  inferencePool:
    create: false
    name: gaie-inference-scheduling

  httpRoute:
    create: true

  epp:
    create: false

decode:
  create: true
  replicas: 2
  nodeSelector:
    cloud.google.com/gke-tpu-topology: "2x4"
    cloud.google.com/gke-tpu-accelerator: "tpu-v6e-slice"
  monitoring:
    podmonitor:
      enabled: false
      portName: "metrics"  # decode vLLM service port (from routing.proxy.targetPort)
      path: "/metrics"
      interval: "30s"
  containers:
  - name: "vllm"
    image: "vllm/vllm-tpu:e92694b6fe264a85371317295bca6643508034ef"
    modelCommand: vllmServe
    args:
      - "--tensor-parallel-size=8"
      - "--max-model-len=4096"
    ports:
      - containerPort: 5557
        protocol: TCP
      - containerPort: 8200
        name: metrics
        protocol: TCP
    resources:
      limits:
        google.com/tpu: 8
      requests:
        google.com/tpu: 8
    mountModelVolume: true
    volumeMounts:
    - name: metrics-volume
      mountPath: /.config
    - name: torch-compile-cache
      mountPath: /.cache
  volumes:
  - name: metrics-volume
    emptyDir: {}
  - name: torch-compile-cache
    emptyDir: {}


# The prefill replica is disabled via 'create: false' since pd is not
# enabled for this configuration, uncomment to deploy a p replica
prefill:
  create: false
  replicas: 0
  monitoring:
    podmonitor:
      enabled: false
      portName: "metrics"  # prefill vLLM service port (from routing.servicePort)
      path: "/metrics"
      interval: "30s"
  containers:
  - name: "vllm"
    image: "ghcr.io/llm-d/llm-d:v0.2.0"
    modelCommand: vllmServe
    args:
      - "--enforce-eager"
      - "--kv-transfer-config"
      - '{"kv_connector":"NixlConnector", "kv_role":"kv_both"}'
    env:
      - name: CUDA_VISIBLE_DEVICES
        value: "0"
      - name: UCX_TLS
        value: "cuda_ipc,cuda_copy,tcp"
      - name: VLLM_NIXL_SIDE_CHANNEL_PORT
        value: "5557"
      - name: VLLM_NIXL_SIDE_CHANNEL_HOST
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      - name: VLLM_LOGGING_LEVEL
        value: DEBUG
    ports:
      - containerPort: 5557
        protocol: TCP
      - containerPort: 8000
        name: metrics
        protocol: TCP
    resources:
      limits:
        nvidia.com/gpu: "1"
      requests:
        nvidia.com/gpu: "1"
    mountModelVolume: true
    volumeMounts:
    - name: metrics-volume
      mountPath: /.config
    - name: torch-compile-cache
      mountPath: /.cache
  volumes:
  - name: metrics-volume
    emptyDir: {}
  - name: torch-compile-cache
    emptyDir: {}
