# repositories:
#   - name: llm-d-infra-repo
#     url: https://github.com/llm-d-incubation/llm-d-infra
#   - name: llm-d-modelservice-repo
#     url: https://github.com/llm-d-incubation/llm-d-modelservice
#   - name: gie-inferencepool-repo
#     url: https://github.com/kubernetes-sigs/gateway-api-inference-extension/blob/main/config/charts/inferencepool

releases:
  - name: istio-base
    namespace: istio-system
    chart: oci://gcr.io/istio-testing/charts/base
    version: 1.27-alpha.0551127f00634403cddd4634567e65a8ecc499a7
    createNamespace: true
    installed: true

  - name: istiod
    namespace: istio-system
    chart: oci://gcr.io/istio-testing/charts/istiod
    version: 1.27-alpha.0551127f00634403cddd4634567e65a8ecc499a7
    installed: true
    wait: true
    set:
      - name: tag
        value: 1.27-alpha.0551127f00634403cddd4634567e65a8ecc499a7
      - name: hub
        value: gcr.io/istio-testing

  - name: infra-facebook
    namespace: llm-d
    chart: ../../charts/llm-d-infra/
    installed: true
    needs:
      - istio-system/istio-base
      - istio-system/istiod
    values:
      - llm-d-infra/istio-values.yaml

  - name: ms-facebook
    namespace: llm-d
    chart: git::https://github.com/llm-d-incubation/llm-d-modelservice.git//charts/llm-d-modelservice?ref=llm-d-modelservice-0.0.8
    version: 0.0.8
    installed: true
    needs:
      - llm-d/infra-facebook
    values:
      - ms-facebook/values.yaml

  - name: gaie-facebook
    namespace: llm-d
    chart: oci://us-central1-docker.pkg.dev/k8s-staging-images/gateway-api-inference-extension/charts/inferencepool
    version: v0
    installed: true
    needs:
      - llm-d/infra-facebook
    values:
      - gaie-facebook/values.yaml
