repositories:
  - name: llm-d-modelservice
    url: https://llm-d-incubation.github.io/llm-d-modelservice/

releases:
  - name: infra-facebook
    namespace: llm-d
    chart: oci://ghcr.io/llm-d-incubation/llm-d-infra/llm-d-infra
    version: 1.0.1
    installed: true
    labels:
      managedBy: llm-d-infra-installer

  - name: ms-facebook
    namespace: llm-d
    chart: llm-d-modelservice/llm-d-modelservice
    version: 0.0.10
    installed: true
    needs:
      - llm-d/infra-facebook
    values:
      - ms-facebook/values.yaml
    labels:
      managedBy: helmfile

  - name: gaie-facebook
    namespace: llm-d
    chart: oci://us-central1-docker.pkg.dev/k8s-staging-images/gateway-api-inference-extension/charts/inferencepool
    version: v0
    installed: true
    needs:
      - llm-d/infra-facebook
    values:
      - gaie-facebook/values.yaml
    labels:
      managedBy: helmfile
